name: Streamlit App Test

on:  
  workflow_dispatch:
  # schedule:  
  # - cron: "0 0 * * *"
  push:  
    branches: [main]
  pull_request:  
    branches: [main]

permissions:
  contents: read

jobs:  
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5   
      with:  
        python-version: "3.12"
    - uses: streamlit/streamlit-app-action@v0.0.3
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      with:  
        app-path: app.py
        pytest-args: -v --junit-xml=test-results.xml
    - if: always()
      uses: pmeier/pytest-results-action@v0.6.0
      with:  
        path: test-results.xml
        summary: true
        display-options: fEsp
    
